// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package http

import (
	fheader "github.com/lemon4ksan/foundation/net/http/header"
)

const (
	HeaderAccept                          = fheader.Accept
	HeaderAcceptCH                        = "Accept-CH"
	HeaderAcceptCharset                   = fheader.AcceptCharset
	HeaderAcceptCHLifetime                = "Accept-CH-Lifetime"
	HeaderAcceptEncoding                  = fheader.AcceptEncoding
	HeaderAcceptLanguage                  = fheader.AcceptLanguage
	HeaderAcceptPatch                     = "Accept-Patch"
	HeaderAcceptPushPolicy                = "Accept-Push-Policy"
	HeaderAcceptRanges                    = fheader.AcceptRanges
	HeaderAcceptSignature                 = "Accept-Signature"
	HeaderAccessControlAllowCredentials   = fheader.AccessControlAllowCredentials
	HeaderAccessControlAllowHeaders       = fheader.AccessControlAllowHeaders
	HeaderAccessControlAllowMethods       = fheader.AccessControlAllowMethods
	HeaderAccessControlAllowOrigin        = fheader.AccessControlAllowOrigin
	HeaderAccessControlExposeHeaders      = fheader.AccessControlExposeHeaders
	HeaderAccessControlMaxAge             = fheader.AccessControlMaxAge
	HeaderAccessControlRequestHeaders     = fheader.AccessControlRequestHeaders
	HeaderAccessControlRequestMethod      = fheader.AccessControlRequestMethod
	HeaderAge                             = fheader.Age
	HeaderAllow                           = fheader.Allow
	HeaderAltSvc                          = fheader.AltSvc
	HeaderAuthorization                   = fheader.Authorization
	HeaderCacheControl                    = fheader.CacheControl
	HeaderClearSiteData                   = fheader.ClearSiteData
	HeaderConnection                      = fheader.Connection
	HeaderContentDisposition              = fheader.ContentDisposition
	HeaderContentDPR                      = "Content-DPR"
	HeaderContentEncoding                 = fheader.ContentEncoding
	HeaderContentLanguage                 = fheader.ContentLanguage
	HeaderContentLength                   = fheader.ContentLength
	HeaderContentLocation                 = fheader.ContentLocation
	HeaderContentRange                    = fheader.ContentRange
	HeaderContentSecurityPolicy           = fheader.ContentSecurityPolicy
	HeaderContentSecurityPolicyReportOnly = fheader.ContentSecurityPolicyReportOnly
	HeaderContentType                     = fheader.ContentType
	HeaderCookie                          = fheader.Cookie
	HeaderCookie2                         = "Cookie2"
	HeaderCrossOriginResourcePolicy       = fheader.CrossOriginResourcePolicy
	HeaderDate                            = fheader.Date
	HeaderDNT                             = "DNT"
	HeaderDPR                             = "DPR"
	HeaderEarlyData                       = "Early-Data"
	HeaderETag                            = fheader.ETag
	HeaderExpect                          = fheader.Expect
	HeaderExpectCT                        = "Expect-CT"
	HeaderExpires                         = fheader.Expires
	HeaderFeaturePolicy                   = "Feature-Policy"
	HeaderForwarded                       = fheader.Forwarded
	HeaderFrom                            = fheader.From
	HeaderHost                            = fheader.Host
	HeaderIfMatch                         = fheader.IfMatch
	HeaderIfModifiedSince                 = fheader.IfModifiedSince
	HeaderIfNoneMatch                     = fheader.IfNoneMatch
	HeaderIfRange                         = fheader.IfRange
	HeaderIfUnmodifiedSince               = fheader.IfUnmodifiedSince
	HeaderIndex                           = "Index"
	HeaderKeepAlive                       = "Keep-Alive"
	HeaderLargeAllocation                 = "Large-Allocation"
	HeaderLastEventID                     = "Last-Event-ID"
	HeaderLastModified                    = fheader.LastModified
	HeaderLink                            = "Link"
	HeaderLocation                        = fheader.Location
	HeaderMaxForwards                     = fheader.MaxForwards
	HeaderNEL                             = "NEL"
	HeaderOrigin                          = fheader.Origin
	HeaderPingFrom                        = "Ping-From"
	HeaderPingTo                          = "Ping-To"
	HeaderPragma                          = fheader.Pragma
	HeaderProxyAuthenticate               = fheader.ProxyAuthenticate
	HeaderProxyAuthorization              = fheader.ProxyAuthorization
	HeaderProxyConnection                 = "Proxy-Connection"
	HeaderPublicKeyPins                   = "Public-Key-Pins"
	HeaderPublicKeyPinsReportOnly         = "Public-Key-Pins-Report-Only"
	HeaderPushPolicy                      = "Push-Policy"
	HeaderRange                           = fheader.Range
	HeaderReferer                         = fheader.Referer
	HeaderReferrerPolicy                  = fheader.ReferrerPolicy
	HeaderReportTo                        = "Report-To"
	HeaderRetryAfter                      = fheader.RetryAfter
	HeaderSaveData                        = "Save-Data"
	HeaderSecWebSocketAccept              = fheader.SecWebSocketAccept
	HeaderSecWebSocketExtensions          = fheader.SecWebSocketExtensions // #nosec G101
	HeaderSecWebSocketKey                 = fheader.SecWebSocketKey
	HeaderSecWebSocketProtocol            = fheader.SecWebSocketProtocol
	HeaderSecWebSocketVersion             = fheader.SecWebSocketVersion
	HeaderServer                          = fheader.Server
	HeaderServerTiming                    = "Server-Timing"
	HeaderSetCookie                       = fheader.SetCookie
	HeaderSignature                       = "Signature"
	HeaderSignedHeaders                   = "Signed-Headers"
	HeaderSourceMap                       = "SourceMap"
	HeaderStrictTransportSecurity         = fheader.StrictTransportSecurity
	HeaderTE                              = fheader.TE
	HeaderTimingAllowOrigin               = "Timing-Allow-Origin"
	HeaderTk                              = "Tk"
	HeaderTrailer                         = fheader.Trailer
	HeaderTransferEncoding                = fheader.TransferEncoding
	HeaderUpgrade                         = fheader.Upgrade
	HeaderUpgradeInsecureRequests         = fheader.UpgradeInsecureRequests
	HeaderUserAgent                       = fheader.UserAgent
	HeaderVary                            = fheader.Vary
	HeaderVia                             = fheader.Via
	HeaderViewportWidth                   = "Viewport-Width"
	HeaderWarning                         = fheader.Warning
	HeaderWidth                           = "Width"
	HeaderWWWAuthenticate                 = fheader.WWWAuthenticate
	HeaderXContentTypeOptions             = fheader.XContentTypeOptions
	HeaderXDNSPrefetchControl             = "X-DNS-Prefetch-Control"
	HeaderXDownloadOptions                = "X-Download-Options"
	HeaderXForwardedFor                   = "X-Forwarded-For"
	HeaderXForwardedHost                  = "X-Forwarded-Host"
	HeaderXForwardedProto                 = "X-Forwarded-Proto"
	HeaderXFrameOptions                   = fheader.XFrameOptions
	HeaderXPermittedCrossDomainPolicies   = "X-Permitted-Cross-Domain-Policies"
	HeaderXPingback                       = "X-Pingback"
	HeaderXPoweredBy                      = "X-Powered-By"
	HeaderXRequestedWith                  = "X-Requested-With"
	HeaderXRobotsTag                      = "X-Robots-Tag"
	HeaderXUACompatible                   = "X-UA-Compatible"
	HeaderXXSSProtection                  = fheader.XXSSProtection
)
