// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package zerocopy

var (
	DefaultServerName  = "foundation"
	DefaultUserAgent   = "foundation"
	DefaultContentType = []byte("text/plain; charset=utf-8")
)

var (
	StrSlash                    = []byte("/")
	StrSlashSlash               = []byte("//")
	StrSlashDotDot              = []byte("/..")
	StrSlashDotSlash            = []byte("/./")
	StrSlashDotDotSlash         = []byte("/../")
	StrBackSlashDotDot          = []byte(`\..`)
	StrBackSlashDotBackSlash    = []byte(`\.\`)
	StrSlashDotDotBackSlash     = []byte(`/..\`)
	StrBackSlashDotDotBackSlash = []byte(`\..\`)
	StrCRLF                     = []byte("\r\n")
	StrCRLFCRLF                 = []byte("\r\n\r\n")
	StrHTTP                     = []byte("http")
	StrHTTPS                    = []byte("https")
	StrHTTP11                   = []byte("HTTP/1.1")
	StrColon                    = []byte(":")
	StrColonSlashSlash          = []byte("://")
	StrColonSpace               = []byte(": ")
	StrCommaSpace               = []byte(", ")
	StrGMT                      = []byte("GMT")
	StrSpace                    = []byte(" ")

	StrResponseContinue = []byte("HTTP/1.1 100 Continue\r\n\r\n")
	StrEarlyHints       = []byte("HTTP/1.1 103 Early Hints\r\n")

	StrExpect             = []byte("Expect")
	StrConnection         = []byte("Connection")
	StrContentLength      = []byte("Content-Length")
	StrContentType        = []byte("Content-Type")
	StrDate               = []byte("Date")
	StrHost               = []byte("Host")
	StrReferer            = []byte("Referer")
	StrServer             = []byte("Server")
	StrTransferEncoding   = []byte("Transfer-Encoding")
	StrContentEncoding    = []byte("Content-Encoding")
	StrAcceptEncoding     = []byte("Accept-Encoding")
	StrUserAgent          = []byte("User-Agent")
	StrCookie             = []byte("Cookie")
	StrSetCookie          = []byte("Set-Cookie")
	StrLocation           = []byte("Location")
	StrIfModifiedSince    = []byte("If-Modified-Since")
	StrLastModified       = []byte("Last-Modified")
	StrAcceptRanges       = []byte("Accept-Ranges")
	StrRange              = []byte("Range")
	StrContentRange       = []byte("Content-Range")
	StrAuthorization      = []byte("Authorization")
	StrTE                 = []byte("TE")
	StrTrailer            = []byte("Trailer")
	StrMaxForwards        = []byte("Max-Forwards")
	StrProxyConnection    = []byte("Proxy-Connection")
	StrProxyAuthenticate  = []byte("Proxy-Authenticate")
	StrProxyAuthorization = []byte("Proxy-Authorization")
	StrWWWAuthenticate    = []byte("WWW-Authenticate")
	StrVary               = []byte("Vary")

	StrCookieExpires        = []byte("expires")
	StrCookieDomain         = []byte("domain")
	StrCookiePath           = []byte("path")
	StrCookieHTTPOnly       = []byte("HttpOnly")
	StrCookieSecure         = []byte("secure")
	StrCookiePartitioned    = []byte("Partitioned")
	StrCookieMaxAge         = []byte("max-age")
	StrCookieSameSite       = []byte("SameSite")
	StrCookieSameSiteLax    = []byte("Lax")
	StrCookieSameSiteStrict = []byte("Strict")
	StrCookieSameSiteNone   = []byte("None")

	StrClose               = []byte("close")
	StrGzip                = []byte("gzip")
	StrBr                  = []byte("br")
	StrZstd                = []byte("zstd")
	StrDeflate             = []byte("deflate")
	StrKeepAlive           = []byte("keep-alive")
	StrUpgrade             = []byte("Upgrade")
	StrChunked             = []byte("chunked")
	StrIdentity            = []byte("identity")
	Str100Continue         = []byte("100-continue")
	StrPostArgsContentType = []byte("application/x-www-form-urlencoded")
	StrDefaultContentType  = []byte("application/octet-stream")
	StrMultipartFormData   = []byte("multipart/form-data")
	StrBoundary            = []byte("boundary")
	StrBytes               = []byte("bytes")
	StrBasicSpace          = []byte("Basic ")
	StrLink                = []byte("Link")
	StrConnect             = []byte("CONNECT")

	StrApplicationSlash = []byte("application/")
	StrImageSVG         = []byte("image/svg")
	StrImageIcon        = []byte("image/x-icon")
	StrFontSlash        = []byte("font/")
	StrMultipartSlash   = []byte("multipart/")
	StrTextSlash        = []byte("text/")
)
